#!/usr/bin/env python3
"""Generate exact-line documentation for Flyto2 Code Python automation."""

from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "reference" / "python-automation.md"
HEADER = "<!-- Generated by scripts/generate-python-reference.py; do not edit. -->\n\n"


def summary(node: ast.AST, name: str) -> str:
    """Return a declaration docstring summary or a stable responsibility phrase."""
    doc = ast.get_docstring(node, clean=True)
    if doc:
        return re.sub(r"\s+", " ", doc.split("\n", 1)[0]).replace("|", "\\|")
    words = re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", name.lstrip("_"))
    words = words.replace("_", " ").strip().lower() or "automation contract"
    return f"Implements {words} for repository verification or maintenance."


def declarations() -> list[dict[str, object]]:
    """Collect Python classes, functions, async functions, and methods under scripts."""
    rows: list[dict[str, object]] = []
    for path in sorted((ROOT / "scripts").rglob("*.py")):
        if "__pycache__" in path.parts:
            continue
        text = path.read_text(encoding="utf-8")
        lines = text.splitlines()
        tree = ast.parse(text)
        relative = path.relative_to(ROOT).as_posix()
        for node in ast.walk(tree):
            if not isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            opening = lines[node.lineno - 1].strip() if node.lineno <= len(lines) else node.name
            opening = re.sub(r"\s+", " ", opening).replace("|", "\\|").replace("`", "&#96;")
            rows.append({
                "kind": "class" if isinstance(node, ast.ClassDef) else "function",
                "name": node.name,
                "path": relative,
                "line": int(node.lineno),
                "signature": opening,
                "summary": summary(node, node.name),
            })
    return sorted(rows, key=lambda row: (str(row["path"]), int(row["line"]), str(row["name"])))


def render() -> str:
    """Render a deterministic Markdown table for every Python declaration."""
    rows = declarations()
    lines = [
        "# Python Automation Reference",
        "",
        f"Exact-line reference for **{len(rows)} declarations** across "
        f"**{len({str(row['path']) for row in rows})} Python automation files**.",
        "",
        "| Kind | Declaration | Responsibility | Source |",
        "|---|---|---|---|",
    ]
    for row in rows:
        source = f"[`{row['path']}:{row['line']}`](<../../{row['path']}#L{row['line']}>)"
        lines.append(
            f"| {row['kind']} | `{row['signature']}` | {row['summary']} | {source} |"
        )
    return HEADER + "\n".join(lines) + "\n"


def main() -> int:
    """Write the generated reference or fail when checked-in output has drifted."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            print(f"generated reference is stale: {OUTPUT.relative_to(ROOT)}", file=sys.stderr)
            return 1
        print("Python automation reference: PASS")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
