// Code generated by cmd/gen-event-types. DO NOT EDIT.
//
// Source: flyto-engine/internal/liveevent/hub.go
//
// To regenerate after adding a new event constant in the engine:
//
//   cd flyto-engine && go run ./cmd/gen-event-types
//
// Importing this file (or the EngineEventType union) gives the
// frontend an exhaustive list of every SSE event the backend can
// emit. Use it as the discriminant in useOrgEvents and assert
// exhaustiveness in the switch default.

export const ENGINE_EVENT_TYPES = [
  // Shared — audit & activity
  'activity.logged',
  // Code — AI Governance lifecycle/runtime closure. Published when the
  // use-case register changes or the governance overlay records a runtime gap,
  // hold, or block so open governance pages can invalidate without polling.
  'ai_governance.changed',
  // Code — AI auto-remediation. Published after a scan completes and
  // the AI has opened draft PRs for top findings, so the UI can show
  // "AI-generated PR" links without polling. Payload: pr_urls [].
  'ai_patch.ready',
  'alert.created',
  'alert.resolved',
  // Code — AutoFix. Published after a Tier 1/2 run completes and
  // findings are persisted so the UI can refresh the AutoFix count
  // badge without manual page reload.
  'autofix.complete',
  // Code — red team campaign budget breach. Published per-org when
  // a CampaignBudgetPolicy threshold is crossed. Payload includes
  // incident_id, policy_id, threshold_type ("soft"|"hard"), metric,
  // observed, limit. UI surfaces as a banner in the war room.
  'campaign_budget.breach',
  // Code — red team campaign execution state transition pushed by
  // the runner via /runner/executions/callback. Lets the UI stop
  // polling — subscribing to this stream is enough to see every
  // queued → running → complete|failed transition within ~1 s.
  // Payload: campaign_execution_id, runner_execution_id, status,
  // verdict?, findings_count?, critical_count?.
  'campaign_execution.updated',
  // Code — capability snapshot changed for an org. Published after
  // entitlement, project type, or membership role mutations that can change
  // GET /api/v1/me/capabilities. Frontend invalidates capability-driven
  // route/nav/settings caches immediately instead of showing stale gates.
  'capabilities.changed',
  'cloud.scan.complete',
  // EventCompanyScopeUpdated — company/business-scope graph changed
  // (holding company, subsidiary, brand, app, declared seed assets).
  // FE invalidates Footprint, Asset Coverage, Brand Protection, CTEM,
  // findings, report and score surfaces from the same Resource Kernel
  // source of truth. Payload: {org_id, source, scope_mode, entities,
  // assets, relationships}.
  'company_scope.updated',
  // Code — domain-specific scan completion. Published once a domain's
  // scan + scoring finishes so the frontend can invalidate the matching
  // posture/findings query keys without waiting for staleTime. Workspace
  // bucket = org_id; payload {org_id}.
  // EventContainerScanComplete: FE invalidates container posture + findings
  // EventCloudScanComplete:     FE invalidates cloud posture + cspm findings
  // EventIdentityScanComplete:  FE invalidates identity posture
  'container.scan.complete',
  // Code — continuous monitoring change detection.
  'discovery.changes',
  'discovery.complete',
  // Code — attack-surface discovery. Published per-step as each scanner
  // completes so the frontend can refresh individual tiles without
  // waiting for the whole fan-out. asset_type in the payload tells the
  // client which tab to invalidate (ssl_cert / tech_stack / whois / …).
  'discovery.started',
  'discovery.step',
  // EventDiscoveryStepFailed — published when a per-asset scanner
  // goroutine panics or its outer timeout cancels it before it can
  // write a row. Without this the UI shows partial data with no
  // "we tried but failed" signal. Payload: {project_id, domain,
  // asset_type, reason}.
  'discovery.step_failed',
  // EventDiscoveryTruncated — published when the per-subdomain
  // cascade is capped (e.g. domain has 50 subdomains, we only run
  // the cascade on the first 8). Payload: {project_id, domain,
  // total_subdomains, cascaded}. UI shows a "we scanned N of M"
  // badge so operators know to manually trigger a cascade for the
  // rest if they want them covered.
  'discovery.truncated',
  // EventExternalIssueUpdated — external CTEM issue state change
  // (mark-fixed / assign / verify). Published after the handlers_ctem
  // status mutations. FE invalidates ctem priorities + external posture.
  // Payload: {org_id, issue_id, action}.
  'external_issue.updated',
  // EventFindingLifecycle — durable finding history changed. Published
  // after created/reconfirmed/field_changed/commented/resolved/
  // verified_fixed/reopened/superseded writes so CTEM pages refresh
  // their list, drawer, footprint overlay and manager rollups without
  // waiting for staleTime. Payload:
  // {org_id, finding_id, fingerprint, action, source, occurred_at}.
  'finding.lifecycle',
  'folder.created',
  'folder.deleted',
  'folder.updated',
  'footprint.breakthrough.updated',
  'footprint.entity.found',
  'footprint.round.complete',
  'footprint.run.finalized',
  // Code — Footprint Expander multi-round expansion. Workspace
  // bucket = org_id, payloads carry the live run snapshot so the
  // frontend can render Round X/Y + entities/tokens/sources
  // without re-fetching latest-run on every tick.
  // EventFootprintRunStarted:    payload {run_id, max_depth, max_entities}
  // EventFootprintEntityFound:   payload {entity_id, type, canonical_name, source, score, tier, depth}
  // EventFootprintRoundComplete: payload {round, entities, tokens_harvested, sources_active}
  // EventFootprintRunFinalized:  payload {run_id, status, stop_reason, entities, relationships, rounds, tokens}
  'footprint.run.started',
  'identity.scan.complete',
  // Integration health — fired when probeGitHub detects an
  // expired or missing GitHub credential. Frontend uses this
  // to instantly raise the IntegrationHealthBanner without
  // waiting for the next health-probe poll.
  'integration.expired',
  // EventIssueStatusChanged — code-issue lifecycle (snooze/ignore/solve).
  // Published after UpsertIssueStatus. FE invalidates enriched issues +
  // autofix findings. Payload: {org_id, fingerprint, status}.
  'issue.status_changed',
  // Code — MCP Runtime Guardian. Published after an MCP call attempt is
  // decided + recorded, whether it arrived from the external MCP proxy's
  // API-key ingest path or from the dashboard's test-connection action.
  // Frontend refreshes overview/egress so open pages reflect live agent
  // traffic without polling.
  'mcp.event.ingested',
  // EventPentestProjectCreated / EventPentestProjectDeleted — pentest
  // project lifecycle (distinct from Cortex project.* events). Payload:
  // {org_id, project_id}.
  'pentest_project.created',
  'pentest_project.deleted',
  'pipeline.complete',
  'pipeline.failed',
  'pipeline.progress',
  // Code — 5-phase red team pipeline state machine. Phase A of the
  // browser→engine orchestrator migration emits these from the log
  // handlers; Phase C will emit them from the engine-side goroutine
  // directly. Workspace bucket = org_id.
  // EventPipelineRunCreated:  payload {run_id, campaign_id, target_url}
  // EventPipelinePhase:       payload {run_id, phase, status, summary?,
  // next_action?, input_tokens, output_tokens}
  // EventPipelineEvidence:    payload {run_id, phase, url, method,
  // status_code?, execution_id?}
  // EventPipelineRunFinalized: payload {run_id, status, risk_level?,
  // proven_count, flaky_count,
  // total_input_tokens, total_output_tokens,
  // error?}
  'pipeline_run.created',
  'pipeline_run.evidence',
  'pipeline_run.finalized',
  'pipeline_run.phase',
  'project.created',
  'project.deleted',
  'project.updated',
  // EventRepoConnected / EventRepoDisconnected — asset ingest signal so a
  // second war-room tab sees the connect/disconnect without staleTime.
  // Payload: {org_id, repo_id}.
  'repo.connected',
  'repo.disconnected',
  // Code — cross-surface remediation. Payload: {event, target_id, plan_id, run_id}.
  'remediation.changed',
  // Cortex — knowledge workspace
  'resource.created',
  'resource.deleted',
  'resource.updated',
  // EventRuntimeEvent — runtime SDK telemetry landed. FE invalidates the
  // runtime view. Payload: {org_id}.
  'runtime.event',
  'scan.complete',
  'scan.failed',
  // Code — scanning & alerting
  'scan.queued',
  'scan.running',
  // EventScanStalled — published by the stalled-scan sweep worker
  // when a queued/running row's started_at is older than the
  // freshness threshold (engine crash, dropped scan.complete,
  // worker pod restart). Frontend treats it like scan.failed for
  // the purpose of invalidating ['repo-scans', repo_id] / the
  // pentest equivalent, but renders a distinct "Stalled" badge
  // with a "Retry" affordance instead of an error message.
  'scan.stalled',
  // Code — score transition monitoring. Published after an alert-worthy
  // score transition is durably saved to monitoring_events so open
  // scoring/Pulse/posture surfaces refresh without polling.
  'score.changed',
  // EventThreatIntelRefresh — global catalog refresh (MITRE actors/malware,
  // ransomware.live) landed new rows. Broadcast to all orgs so open
  // threat-intel pages refresh. Payload: {catalog, count}.
  'threatintel.refresh',
  // Code — closed-loop verification.
  'verify.dispatched',
  'verify.terminal',
] as const

export type EngineEventType = typeof ENGINE_EVENT_TYPES[number]

/**
 * Compile-time exhaustiveness check. Use in the default branch of
 * a switch on event.type:
 *
 *   switch (e.type as EngineEventType) {
 *     case 'scan.queued': …
 *     default: assertExhaustiveEvent(e.type as never)
 *   }
 *
 * The 'never' parameter type means a missing case is a TypeScript
 * compile error — adding a new event server-side without handling it
 * here breaks CI immediately.
 *
 * At runtime we warn instead of throwing so an engine that ships
 * ahead of the frontend (e.g. a canary deploy emitting a brand-new
 * event type) doesn't crash users' tabs. The compile-time bound is
 * what catches the bug class; the runtime is intentionally lenient.
 */
export function assertExhaustiveEvent(t: never): void {
  if (import.meta.env.DEV) {
    console.warn('[engine-events] unhandled event type:', t)
  }
}
