import type { AssetCoverageResponse } from '@lib/engine/code/assetCoverage'

export const assetCoverageFixture: AssetCoverageResponse = {
  orgId: 'org-1',
  generatedAt: '2026-06-17T05:00:00Z',
  policy: {
    resourceInclusion: 'confirmed_only',
    candidateHandling: 'quarantine_until_confirmed',
    uncertaintyRendering: 'debt_not_absence',
    absentNotCollectedMeaning: 'not_collected_is_unknown',
    unavailableSourceTreatment: 'source_debt',
  },
  rollup: {
    confirmedResources: 2,
    quarantinedCandidates: 1,
    sourceCount: 3,
    sourceStatusCounts: { fresh: 1, stale: 1, error: 1 },
    claimStateCounts: { present: 1, stale: 1, error: 1 },
    totalResourceSourcePairs: 6,
    answeredPairs: 3,
    presentPairs: 1,
    vendorEmptyPairs: 1,
    notApplicablePairs: 1,
    errorPairs: 1,
    stalePairs: 1,
    unavailablePairs: 0,
    notCollectedPairs: 1,
    uncertaintyDebtPairs: 3,
    uncertaintyDebtPercentage: 50,
  },
  scope: {
    state: 'incomplete',
    rollup: {
      requiredEntities: 3,
      coveredEntities: 1,
      entitiesWithDebt: 2,
      candidateEntities: 0,
      unlinkedResources: 1,
      quarantinedAssets: 1,
      scopeDebtItems: 4,
      scopeDebtPercentage: 67,
      totalEntitySourceRows: 6,
      entitySourceDebtRows: 3,
    },
    entities: [
      {
        id: 'ent-holding',
        kind: 'organization',
        legalName: 'Cathay Financial Holding',
        displayName: 'Cathay Financial Holding',
        canonicalValue: 'cathay financial holding',
        status: 'active',
        verificationState: 'confirmed',
        required: true,
        aliases: ['Cathay FHC'],
        seedDomains: ['cathayholdings.com'],
        sourceStates: [
          { sourceId: 'crtsh', sourceLabel: 'Certificate Transparency', status: 'fresh', totalPairs: 1, answeredPairs: 1, debtPairs: 0 },
          { sourceId: 'shodan', sourceLabel: 'Shodan InternetDB', status: 'error', totalPairs: 1, answeredPairs: 0, debtPairs: 1 },
        ],
        resources: [
          {
            id: 'res:www',
            category: 'domain',
            type: 'hostname',
            canonicalValue: 'www.example.com',
            displayName: 'www.example.com',
            status: 'active',
            reviewStatus: 'manual_confirmed',
            confidenceScore: 90,
            lastSeenAt: '2026-06-17T03:00:00Z',
          },
        ],
        debt: [
          {
            kind: 'source_debt',
            severity: 'high',
            message: 'Shodan InternetDB has 1 unanswered pair(s) for this entity.',
            nextAction: 'Run, configure, or refresh this source before treating the entity as fully covered.',
            entityId: 'ent-holding',
            sourceId: 'shodan',
          },
        ],
      },
      {
        id: 'ent-bank',
        parentId: 'ent-holding',
        kind: 'organization',
        legalName: 'Cathay United Bank',
        displayName: 'Cathay United Bank',
        canonicalValue: 'cathay united bank',
        status: 'active',
        verificationState: 'confirmed',
        required: true,
        sourceStates: [
          { sourceId: 'crtsh', sourceLabel: 'Certificate Transparency', status: 'fresh', totalPairs: 1, answeredPairs: 1, debtPairs: 0 },
          { sourceId: 'shodan', sourceLabel: 'Shodan InternetDB', status: 'error', totalPairs: 1, answeredPairs: 0, debtPairs: 1 },
        ],
        resources: [
          {
            id: 'res:api',
            category: 'domain',
            type: 'hostname',
            canonicalValue: 'api.example.com',
            displayName: 'api.example.com',
            status: 'active',
            reviewStatus: 'auto_confirmed',
            confidenceScore: 97,
            lastSeenAt: '2026-06-17T04:00:00Z',
          },
        ],
        debt: [
          {
            kind: 'source_debt',
            severity: 'high',
            message: 'Shodan InternetDB has 1 unanswered pair(s) for this entity.',
            nextAction: 'Run, configure, or refresh this source before treating the entity as fully covered.',
            entityId: 'ent-bank',
            sourceId: 'shodan',
          },
        ],
      },
      {
        id: 'ent-insurance',
        parentId: 'ent-holding',
        kind: 'organization',
        legalName: 'Cathay Century Insurance',
        displayName: 'Cathay Century Insurance',
        canonicalValue: 'cathay century insurance',
        status: 'active',
        verificationState: 'confirmed',
        required: true,
        sourceStates: [
          { sourceId: 'crtsh', sourceLabel: 'Certificate Transparency', status: 'fresh', totalPairs: 0, answeredPairs: 0, debtPairs: 0 },
          { sourceId: 'shodan', sourceLabel: 'Shodan InternetDB', status: 'error', totalPairs: 0, answeredPairs: 0, debtPairs: 1 },
        ],
        resources: [],
        debt: [
          {
            kind: 'no_confirmed_resource',
            severity: 'high',
            message: 'Required entity has no confirmed linked assets.',
            nextAction: 'Seed or confirm owned domains, apps, repositories, or infrastructure for this entity.',
            entityId: 'ent-insurance',
          },
        ],
      },
    ],
    unlinkedResources: [
      {
        id: 'res:orphan',
        category: 'domain',
        type: 'hostname',
        canonicalValue: 'orphan.example.com',
        displayName: 'orphan.example.com',
        status: 'active',
        reviewStatus: 'auto_confirmed',
        confidenceScore: 91,
        lastSeenAt: '2026-06-17T02:30:00Z',
      },
    ],
    caveats: ['scope is not complete until every required entity, source, and linked asset has fresh evidence'],
  },
  sources: [
    {
      id: 'crtsh',
      providerId: 'flyto',
      integrationId: 'flyto:crtsh',
      label: 'Certificate Transparency',
      surface: 'external',
      component: 'footprint',
      collectionMode: 'public_api',
      coverageField: 'footprint.certificates',
      outputGroups: ['domain'],
      freshnessSlaHours: 24,
      noisePolicy: 'unknown_error_stale_are_debt',
      status: 'fresh',
      lastAttemptAt: '2026-06-17T04:30:00Z',
    },
    {
      id: 'shodan',
      providerId: 'shodan',
      integrationId: 'shodan:internetdb',
      label: 'Shodan InternetDB',
      surface: 'external',
      component: 'exposure',
      collectionMode: 'api',
      coverageField: 'internetdb.host',
      outputGroups: ['ip'],
      requiredEnvGroups: ['SHODAN_API_KEY'],
      missingEnvGroups: ['SHODAN_API_KEY'],
      freshnessSlaHours: 24,
      noisePolicy: 'unknown_error_stale_are_debt',
      status: 'error',
      detail: 'API key missing',
      caveat: 'Collection failed; this is not evidence of absence.',
      lastAttemptAt: '2026-06-17T04:40:00Z',
    },
  ],
  resources: [
    {
      resource: {
        id: 'res:api',
        category: 'domain',
        type: 'hostname',
        canonicalValue: 'api.example.com',
        displayName: 'api.example.com',
        status: 'active',
        reviewStatus: 'auto_confirmed',
        confidenceScore: 97,
        lastSeenAt: '2026-06-17T04:00:00Z',
      },
      summary: {
        present: 1,
        vendorEmpty: 1,
        notApplicable: 0,
        stale: 1,
        error: 1,
        notCollected: 0,
      },
      claims: [
        {
          id: 'claim-1',
          resourceId: 'res:api',
          field: 'dns.name',
          sourceId: 'crtsh',
          sourceIntegrationId: 'flyto:crtsh',
          sourceLabel: 'Certificate Transparency',
          coverageState: 'present',
          valueKind: 'hostname',
          value: 'api.example.com',
          confidence: 0.96,
          observedAt: '2026-06-17T04:20:00Z',
          mappingVersion: 'v1',
        },
      ],
      caveats: ['Shodan error still needs retry before confidence can be asserted.'],
    },
    {
      resource: {
        id: 'res:www',
        category: 'domain',
        type: 'hostname',
        canonicalValue: 'www.example.com',
        displayName: 'www.example.com',
        status: 'active',
        reviewStatus: 'manual_confirmed',
        confidenceScore: 90,
        lastSeenAt: '2026-06-17T03:00:00Z',
      },
      summary: {
        present: 0,
        vendorEmpty: 0,
        notApplicable: 1,
        stale: 0,
        error: 0,
        notCollected: 1,
      },
      claims: [],
    },
  ],
  quarantine: [
    {
      resource: {
        id: 'res:candidate',
        category: 'domain',
        type: 'hostname',
        canonicalValue: 'cdn-example.net',
        displayName: 'cdn-example.net',
        status: 'candidate',
        reviewStatus: 'quarantined',
        confidenceScore: 42,
        lastSeenAt: '2026-06-17T01:00:00Z',
      },
      certainty: 'low',
      reason: 'single weak source',
    },
  ],
  caveats: ['Coverage debt remains until collection succeeds.'],
}
