#!/usr/bin/env python3
"""Generate source-linked Warroom CE declaration reference pages."""

from __future__ import annotations

import argparse
import ast
import gzip
import json
import re
import sys
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = ROOT / "docs" / "reference"
GENERATED = "<!-- Generated by scripts/generate-documentation-reference.py; do not edit. -->\n\n"
MAX_ROWS = 350
DOCUMENTABLE_TYPES = {"function", "method", "class", "composable"}
SOURCE_SUFFIXES = {".go", ".js", ".mjs", ".cjs", ".ts", ".tsx", ".py"}
EXCLUDED_PARTS = {
    ".flyto-index", ".git", "dist", "dist-next", "node_modules",
    "test-results", "upstream-patches",
}


def source_files() -> list[Path]:
    return sorted(
        path for path in ROOT.rglob("*")
        if path.is_file()
        and path.suffix in SOURCE_SUFFIXES
        and not any(part in EXCLUDED_PARTS for part in path.relative_to(ROOT).parts)
    )


def humanize(name: str) -> str:
    value = name.rsplit(".", 1)[-1].lstrip("_")
    value = re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", value)
    value = value.replace("_", " ").replace("-", " ")
    return re.sub(r"\s+", " ", value).strip().lower() or "source contract"


def responsibility(name: str, relative: str) -> str:
    action = humanize(name)
    first = action.split(" ", 1)[0]
    verbs = (
        (("new", "create", "add"), "Creates"),
        (("get", "load", "read", "fetch", "find", "list", "search"), "Retrieves"),
        (("set", "update", "write", "save", "persist"), "Updates"),
        (("delete", "remove", "clear", "purge"), "Removes"),
        (("validate", "check", "verify", "ensure"), "Validates"),
        (("handle", "serve"), "Handles"),
        (("run", "execute", "start", "dispatch"), "Executes"),
        (("stop", "close", "shutdown"), "Stops"),
        (("build", "make", "compile", "render", "generate"), "Builds"),
        (("parse", "decode", "unmarshal"), "Parses"),
        (("encode", "marshal", "serialize"), "Serializes"),
        (("is", "has", "can", "should"), "Reports whether"),
        (("sync",), "Synchronizes"),
        (("audit",), "Audits"),
        (("register",), "Registers"),
        (("calculate", "compute", "score"), "Calculates"),
        (("publish", "emit", "notify"), "Publishes"),
    )
    for candidates, verb in verbs:
        if any(first.startswith(candidate) for candidate in candidates):
            return f"{verb} {action} for `{relative}`."
    return f"Implements {action} for `{relative}`."


def declaration(kind: str, name: str, path: Path, line: int, source: str) -> dict:
    relative = path.relative_to(ROOT).as_posix()
    return {
        "kind": kind,
        "name": name,
        "path": relative,
        "line": line,
        "signature": re.sub(r"\s+", " ", source.strip()).replace("|", "\\|")[:180],
        "responsibility": responsibility(name, relative),
    }


def python_declarations(path: Path, text: str) -> list[dict]:
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return []
    lines = text.splitlines()
    rows = []
    for node in ast.walk(tree):
        if not isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        line = int(node.lineno)
        kind = "class" if isinstance(node, ast.ClassDef) else "function"
        source = lines[line - 1] if line <= len(lines) else node.name
        rows.append(declaration(kind, node.name, path, line, source))
    return rows


def go_declarations(path: Path, text: str) -> list[dict]:
    rows = []
    patterns = (
        ("function", re.compile(r"^\s*func\s+(?:\([^)]*\)\s*)?([A-Za-z_]\w*)")),
        ("class", re.compile(r"^\s*type\s+([A-Za-z_]\w*)\s+(?:struct|interface)\b")),
    )
    for line_number, source in enumerate(text.splitlines(), start=1):
        for kind, pattern in patterns:
            match = pattern.match(source)
            if match:
                rows.append(declaration(kind, match.group(1), path, line_number, source))
                break
    return rows


def javascript_declarations(path: Path, text: str) -> list[dict]:
    rows = []
    patterns = (
        ("function", re.compile(r"^\s*(?:export\s+)?(?:default\s+)?(?:async\s+)?function\s+([A-Za-z_$][\w$]*)")),
        ("class", re.compile(r"^\s*(?:export\s+)?(?:default\s+)?class\s+([A-Za-z_$][\w$]*)")),
        ("function", re.compile(r"^\s*(?:export\s+)?(?:const|let|var)\s+([A-Za-z_$][\w$]*)\b")),
    )
    for line_number, source in enumerate(text.splitlines(), start=1):
        for kind, pattern in patterns:
            match = pattern.match(source)
            if match:
                rows.append(declaration(kind, match.group(1), path, line_number, source))
                break
    return rows


def declarations() -> list[dict]:
    rows = []
    for path in source_files():
        text = path.read_text(encoding="utf-8", errors="ignore")
        if path.suffix == ".py":
            rows.extend(python_declarations(path, text))
        elif path.suffix == ".go":
            rows.extend(go_declarations(path, text))
        else:
            rows.extend(javascript_declarations(path, text))
    unique = {(row["path"], row["line"]): row for row in rows}
    return sorted(unique.values(), key=lambda row: (row["path"], row["line"], row["name"]))


def render() -> dict[str, str]:
    rows = declarations()
    grouped = defaultdict(list)
    for row in rows:
        grouped[row["path"].split("/", 1)[0]].append(row)
    outputs = {}
    inventory = []
    for area in sorted(grouped):
        area_rows = grouped[area]
        for offset in range(0, len(area_rows), MAX_ROWS):
            chunk = area_rows[offset : offset + MAX_ROWS]
            number = offset // MAX_ROWS + 1
            name = f"source-{area}-{number:02d}.md"
            table = [
                "| Kind | Declaration | Responsibility | Source |",
                "|---|---|---|---|",
            ]
            for row in chunk:
                target = f"../../{row['path']}#L{row['line']}"
                source = f"[`{row['path']}:{row['line']}`](<{target}>)"
                table.append(
                    f"| {row['kind']} | `{row['signature'].replace('`', '&#96;')}` | "
                    f"{row['responsibility']} | {source} |"
                )
            title = f"{area.replace('-', ' ').title()} Source Reference {number}"
            outputs[name] = (
                GENERATED + f"# {title}\n\n"
                + f"Source-linked contracts for **{len(chunk)} declarations** in `{area}/`.\n\n"
                + "\n".join(table) + "\n"
            )
            inventory.append((name, area, len(chunk), len({row["path"] for row in chunk})))
    index_rows = ["| Reference | Area | Declarations | Files |", "|---|---|---:|---:|"]
    for name, area, count, files in inventory:
        index_rows.append(f"| [`{name}`]({name}) | `{area}/` | {count} | {files} |")
    outputs["README.md"] = (
        GENERATED + "# Flyto2 Warroom CE Source Reference\n\n"
        + "This generated index links public classes, functions, methods, and callable "
        + "source declarations to their exact implementation lines. Domain behavior is "
        + "explained in the owning package and feature guides; these pages provide the "
        + "complete implementation-level navigation contract.\n\n"
        + f"Inventory: **{len(rows)} declaration sites** across "
        + f"**{len({row['path'] for row in rows})} source files**.\n\n"
        + "\n".join(index_rows) + "\n"
    )
    return outputs


def indexed_locations() -> set[tuple[str, int]]:
    plain = ROOT / ".flyto-index" / "index.json"
    zipped = ROOT / ".flyto-index" / "index.json.gz"
    try:
        if plain.is_file():
            payload = json.loads(plain.read_text(encoding="utf-8"))
        elif zipped.is_file():
            with gzip.open(zipped, "rt", encoding="utf-8") as handle:
                payload = json.load(handle)
        else:
            return set()
    except (OSError, json.JSONDecodeError):
        return set()
    return {
        (symbol.get("path", ""), int(symbol.get("start_line") or 0))
        for symbol in payload.get("symbols", {}).values()
        if symbol.get("type") in DOCUMENTABLE_TYPES
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = render()
    expected = {OUTPUT_DIR / name: content for name, content in outputs.items()}
    existing = set(OUTPUT_DIR.glob("source-*.md")) | {OUTPUT_DIR / "README.md"}
    if args.check:
        errors = [
            path.relative_to(ROOT).as_posix()
            for path, content in expected.items()
            if not path.is_file() or path.read_text(encoding="utf-8") != content
        ]
        errors.extend(path.relative_to(ROOT).as_posix() for path in existing - set(expected))
        indexed = indexed_locations()
        generated = {(row["path"], row["line"]) for row in declarations()}
        missing = sorted(indexed - generated)
        errors.extend(f"missing indexed declaration: {path}:{line}" for path, line in missing[:30])
        if len(missing) > 30:
            errors.append(f"and {len(missing) - 30} more missing indexed declarations")
        if errors:
            print("documentation reference drift:", file=sys.stderr)
            for error in sorted(set(errors)):
                print(f"- {error}", file=sys.stderr)
            return 1
        print(f"documentation reference is current: {len(indexed)} indexed declarations covered")
        return 0
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for path in existing - set(expected):
        path.unlink()
    for path, content in expected.items():
        path.write_text(content, encoding="utf-8")
    print(f"generated {len(outputs)} reference pages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
