/**
 * Chart type registry — all available visualization types.
 * Each defines what field types it needs and how to render.
 */

import {
  PieChart, BarChart3, LineChart, Radar, Grid3X3,
  Gauge, Table2, Activity, BarChart, CircleDot,
  LayoutGrid, TrendingUp, FileText,
} from 'lucide-react'
import type { ChartTypeDef } from './types'

export const CHART_TYPES: ChartTypeDef[] = [
  {
    type: 'donut',
    name: 'Donut Chart',
    nameKey: 'reports.chart.donut',
    icon: PieChart,
    requiresLabel: true,
    requiresValue: true,
    requiresMultiValue: false,
    supportsTimeSeries: false,
  },
  {
    type: 'bar',
    name: 'Bar Chart',
    nameKey: 'reports.chart.bar',
    icon: BarChart3,
    requiresLabel: true,
    requiresValue: true,
    requiresMultiValue: false,
    supportsTimeSeries: false,
  },
  {
    type: 'stacked-bar',
    name: 'Stacked Bar',
    nameKey: 'reports.chart.stackedBar',
    icon: BarChart,
    requiresLabel: true,
    requiresValue: false,
    requiresMultiValue: true,
    supportsTimeSeries: false,
  },
  {
    type: 'line',
    name: 'Line Chart',
    nameKey: 'reports.chart.line',
    icon: LineChart,
    requiresLabel: true,
    requiresValue: true,
    requiresMultiValue: false,
    supportsTimeSeries: true,
  },
  {
    type: 'area',
    name: 'Area Chart',
    nameKey: 'reports.chart.area',
    icon: TrendingUp,
    requiresLabel: true,
    requiresValue: true,
    requiresMultiValue: false,
    supportsTimeSeries: true,
  },
  {
    type: 'radar',
    name: 'Radar Chart',
    nameKey: 'reports.chart.radar',
    icon: Radar,
    requiresLabel: true,
    requiresValue: false,
    requiresMultiValue: true,
    supportsTimeSeries: false,
  },
  {
    type: 'treemap',
    name: 'Treemap',
    nameKey: 'reports.chart.treemap',
    icon: LayoutGrid,
    requiresLabel: true,
    requiresValue: true,
    requiresMultiValue: false,
    supportsTimeSeries: false,
  },
  {
    type: 'heatmap',
    name: 'Heatmap',
    nameKey: 'reports.chart.heatmap',
    icon: Grid3X3,
    requiresLabel: true,
    requiresValue: true,
    requiresMultiValue: false,
    supportsTimeSeries: false,
  },
  {
    type: 'gauge',
    name: 'Gauge',
    nameKey: 'reports.chart.gauge',
    icon: Gauge,
    requiresLabel: false,
    requiresValue: true,
    requiresMultiValue: false,
    supportsTimeSeries: false,
  },
  {
    type: 'radialBar',
    name: 'Radial Bar',
    nameKey: 'reports.chart.radialBar',
    icon: CircleDot,
    requiresLabel: true,
    requiresValue: true,
    requiresMultiValue: false,
    supportsTimeSeries: false,
  },
  {
    type: 'table',
    name: 'Table',
    nameKey: 'reports.chart.table',
    icon: Table2,
    requiresLabel: false,
    requiresValue: false,
    requiresMultiValue: false,
    supportsTimeSeries: false,
  },
  {
    type: 'kpi',
    name: 'KPI Card',
    nameKey: 'reports.chart.kpi',
    icon: Activity,
    requiresLabel: false,
    requiresValue: true,
    requiresMultiValue: false,
    supportsTimeSeries: false,
  },
  {
    type: 'text',
    name: 'Text Block',
    nameKey: 'reports.chart.text',
    icon: FileText,
    requiresLabel: false,
    requiresValue: false,
    requiresMultiValue: false,
    supportsTimeSeries: false,
  },
]

export const CHART_TYPE_MAP: Record<string, ChartTypeDef> = Object.fromEntries(
  CHART_TYPES.map(ct => [ct.type, ct])
)
