"""
Main indexing engine - orchestrates the entire flow.

Usage:
1. engine.scan() - Scan project, build index
2. engine.impact(symbol_id) - Query impact scope
3. engine.context(query) - Get relevant context (L0->L1->L2)
"""

import json
import logging
import time
from datetime import datetime
from pathlib import Path
from typing import Optional

from .safe_io import atomic_write_text, atomic_write_lines, atomic_write_json

from .context.loader import ContextLoader
from .dependency_resolver import DependencyResolverMixin
from .indexer import IncrementalIndexer, scan_directory_hashes
from .models import Dependency, DependencyType, FileManifest, ProjectIndex, Symbol, SymbolType
from .reverse_index import ReverseIndexMixin
from .scanner import (
    GoScanner,
    JavaScanner,
    PythonScanner,
    RustScanner,
    ScanResult,
    TypeScriptScanner,
    VueScanner,
)
from .search_index import SearchIndexMixin

logger = logging.getLogger(__name__)


_GITIGNORE_CONTENT = "# Auto-generated by flyto-indexer — keep IDE and git from indexing this directory\n*\n"

# Directories that flyto-indexer creates and IDEs should ignore
_INDEX_DIRS = [".flyto-index", ".flyto"]


def _ensure_gitignore(directory: Path):
    """Create .gitignore with '*' in a generated directory if it doesn't exist."""
    gi = directory / ".gitignore"
    if not gi.exists():
        gi.write_text(_GITIGNORE_CONTENT)


def _ensure_ide_exclude(project_root: Path):
    """Auto-exclude .flyto-index/ and .flyto/ from IDE file watchers.

    Supports:
    - JetBrains (WebStorm, IntelliJ, PyCharm): adds <excludeFolder> to .iml files
    - VSCode: adds to files.watcherExclude in .vscode/settings.json

    Also checks the parent directory for monorepo setups where .idea/ lives
    at the workspace root (e.g., flytohub/.idea/) while scanning a sub-project.
    """
    roots = [project_root]
    parent = project_root.parent
    if parent != project_root and (parent / ".idea").is_dir():
        roots.append(parent)

    for root in roots:
        _ensure_jetbrains_exclude(root, project_root)
        _ensure_vscode_exclude(root)


def _ensure_jetbrains_exclude(ide_root: Path, project_root: Path):
    """Add excludeFolder entries to JetBrains .iml files.

    Args:
        ide_root: Directory containing .idea/ (may be workspace root in monorepo)
        project_root: The actual project being indexed
    """
    idea_dir = ide_root / ".idea"
    if not idea_dir.is_dir():
        return

    import glob as glob_mod
    iml_files = glob_mod.glob(str(idea_dir / "*.iml"))
    if not iml_files:
        return

    # Calculate relative path from IDE root to project root
    try:
        rel_prefix = project_root.relative_to(ide_root)
    except ValueError:
        return
    # For monorepo: prefix = "flyto-cloud/", for same dir: prefix = ""
    prefix = str(rel_prefix) + "/" if str(rel_prefix) != "." else ""

    for iml_path in iml_files:
        try:
            content = Path(iml_path).read_text(encoding="utf-8")
        except OSError:
            continue

        modified = False
        for dir_name in _INDEX_DIRS:
            exclude_url = f'file://$MODULE_DIR$/{prefix}{dir_name}'
            # Use exact attribute match to avoid .flyto matching .flyto-index
            if f'url="{exclude_url}"' in content:
                continue

            # Insert before </content> tag
            marker = "</content>"
            if marker not in content:
                continue

            exclude_line = f'      <excludeFolder url="{exclude_url}" />\n'
            content = content.replace(marker, exclude_line + "    " + marker)
            modified = True

        if modified:
            try:
                Path(iml_path).write_text(content, encoding="utf-8")
                logger.info("Added IDE exclude to %s", iml_path)
            except OSError as e:
                logger.debug("Failed to update %s: %s", iml_path, e)


def _ensure_vscode_exclude(project_root: Path):
    """Add entries to .vscode/settings.json files.watcherExclude."""
    vscode_dir = project_root / ".vscode"
    if not vscode_dir.is_dir():
        return

    settings_path = vscode_dir / "settings.json"
    try:
        if settings_path.exists():
            raw = settings_path.read_text(encoding="utf-8")
            settings = json.loads(raw) if raw.strip() else {}
        else:
            settings = {}
    except (OSError, json.JSONDecodeError):
        return

    watcher_exclude = settings.setdefault("files.watcherExclude", {})

    modified = False
    for dir_name in _INDEX_DIRS:
        pattern = f"**/{dir_name}/**"
        if pattern not in watcher_exclude:
            watcher_exclude[pattern] = True
            modified = True

    if modified:
        try:
            settings_path.write_text(
                json.dumps(settings, indent=4, ensure_ascii=False) + "\n",
                encoding="utf-8",
            )
            logger.info("Added IDE exclude to %s", settings_path)
        except OSError as e:
            logger.debug("Failed to update %s: %s", settings_path, e)


class IndexEngine(
    DependencyResolverMixin,
    ReverseIndexMixin,
    SearchIndexMixin,
):
    """
    Indexing engine

    Main features:
    1. scan() - Scan project, incrementally update index
    2. impact() - Query impact scope
    3. context() - Get context (from shallow to deep)
    """

    def __init__(
        self,
        project_name: str,
        project_root: Path,
        index_dir: Optional[Path] = None
    ):
        self.project_name = project_name
        self.project_root = Path(project_root)
        self.index_dir = index_dir or (self.project_root / ".flyto-index")

        # Initialize components
        self.scanners = [
            PythonScanner(project_name),
            VueScanner(project_name),
            TypeScriptScanner(project_name),
            GoScanner(project_name),
            RustScanner(project_name),
            JavaScanner(project_name),
        ]
        self.incremental = IncrementalIndexer(self.project_root, self.index_dir)

        # Load or initialize index
        self.index = self._load_or_create_index()

    def scan(self, incremental: bool = True) -> dict:
        """
        Scan project, build/update index

        Args:
            incremental: Whether to perform incremental update (only update changed files)

        Returns:
            Scan result summary (includes timing breakdown)
        """
        t_total_start = time.monotonic()

        # Collect all supported extensions
        extensions = []
        for scanner in self.scanners:
            extensions.extend(scanner.supported_extensions)

        # Scan directory to get all file hashes
        current_hashes = scan_directory_hashes(
            self.project_root,
            extensions,
            ignore_patterns=[
                "node_modules", "__pycache__", ".git", "dist", "build",
                ".venv", "venv", ".pytest_cache", ".flyto-index", ".flyto"
            ]
        )

        # Detect changes
        if incremental:
            changes = self.incremental.detect_changes(current_hashes)
            files_to_scan = changes.all_changed()
        else:
            # Full rebuild
            changes = None
            files_to_scan = list(current_hashes.keys())
            self.index = self._create_empty_index()

        # Scan files
        t_scan_start = time.monotonic()
        result = ScanResult()
        for rel_path in files_to_scan:
            file_path = self.project_root / rel_path
            if not file_path.exists():
                continue

            # Check file size (skip files larger than 1MB)
            file_size = file_path.stat().st_size
            if file_size > 1_048_576:
                result.add_error(rel_path, f"File too large: {file_size:,} bytes (max 1MB)")
                continue

            # Find the matching scanner
            scanner = self._get_scanner(file_path)
            if not scanner:
                continue

            try:
                content = file_path.read_text(encoding="utf-8")
                symbols, deps = scanner.scan_file(Path(rel_path), content)
                manifest = scanner.create_file_manifest(Path(rel_path), content, symbols)
                result.add_file_result(symbols, deps, manifest)
            except (SyntaxError, UnicodeDecodeError, OSError, ValueError) as e:
                result.add_error(rel_path, str(e))
        t_scan_end = time.monotonic()

        # Update index
        self._update_index(result, changes)

        # Extract changed_paths for incremental downstream processing
        changed_paths = None
        if incremental and changes and not changes.is_empty():
            changed_paths = set(changes.all_changed() + changes.deleted)

        # Resolve dependencies and build reverse index
        t_resolve_start = time.monotonic()
        self._resolve_dependencies(changed_paths=changed_paths)
        self._resolve_go_implementations()
        t_resolve_end = time.monotonic()

        t_reverse_start = time.monotonic()
        self._build_reverse_index(changed_paths=changed_paths)
        t_reverse_end = time.monotonic()

        # Save index + build search indexes
        t_save_start = time.monotonic()
        self._save_index()
        self._update_search_indexes(changed_paths=changed_paths)
        t_save_end = time.monotonic()

        # Apply incremental changes to manifest
        if incremental and changes:
            self.incremental.apply_changes(
                changes,
                result.manifests,
                result.symbols,
                result.dependencies
            )

        t_total_end = time.monotonic()

        return {
            "project": self.project_name,
            "files_scanned": len(files_to_scan),
            "symbols_found": len(result.symbols),
            "dependencies_found": len(result.dependencies),
            "errors": len(result.errors),
            "changes": changes.summary() if changes else "full rebuild",
            "timing": {
                "scan_files": round(t_scan_end - t_scan_start, 3),
                "resolve_deps": round(t_resolve_end - t_resolve_start, 3),
                "build_reverse": round(t_reverse_end - t_reverse_start, 3),
                "save_index": round(t_save_end - t_save_start, 3),
                "total": round(t_total_end - t_total_start, 3),
            },
        }

    def impact(self, symbol_id: str, max_depth: int = 3) -> dict:
        """
        Query impact scope

        If this symbol is changed, which other symbols are affected?

        Args:
            symbol_id: Symbol ID (full or short format)
            max_depth: Maximum traversal depth

        Returns:
            Impact chain structure
        """
        # Try to resolve symbol_id
        full_id = self._resolve_symbol_id(symbol_id)
        if not full_id:
            return {"error": f"Symbol not found: {symbol_id}"}

        # Get impact chain
        chain = self.index.get_impact_chain(full_id, max_depth)
        direct_references = self.index.get_affected_by(full_id)

        # Add symbol info
        result = {
            "symbol": full_id,
            "symbol_info": self.index.symbols[full_id].to_dict() if full_id in self.index.symbols else None,
            "total_direct_references": len(direct_references),
            "direct_references": [],
            "impact_chain": [],
        }

        for sid in direct_references:
            result["direct_references"].append(self._symbol_ref(sid))

        for level in chain["levels"]:
            level_info = {
                "depth": level["depth"],
                "affected": [],
            }
            for sid in level["symbols"]:
                level_info["affected"].append(self._symbol_ref(sid))
            result["impact_chain"].append(level_info)

        return result

    def context(
        self,
        query: Optional[str] = None,
        paths: Optional[list[str]] = None,
        symbols: Optional[list[str]] = None,
        level: str = "auto"
    ) -> dict:
        """
        Get context (from shallow to deep)

        Args:
            query: Natural language query (uses L0 to locate, then fetches L1/L2)
            paths: Specified file paths (directly fetches L1)
            symbols: Specified symbol IDs (directly fetches L2)
            level: "l0", "l1", "l2", or "auto"

        Returns:
            Context content
        """
        loader = ContextLoader(self.index)

        # Always load L0 first (used for locating)
        l0 = loader.load_l0()

        if level == "l0" or (level == "auto" and not query and not paths and not symbols):
            return {
                "level": "l0",
                "content": l0.to_text(),
                "token_estimate": l0.token_estimate(),
            }

        # If symbols are specified, directly fetch L2
        if symbols:
            l2_list = []
            for sid in symbols:
                full_id = self._resolve_symbol_id(sid)
                if full_id:
                    l2 = loader.load_l2(full_id)
                    if l2:
                        l2_list.append(l2)
            return {
                "level": "l2",
                "content": "\n\n---\n\n".join(l2.to_text() for l2 in l2_list),
                "symbols": [l2.symbol_id for l2 in l2_list],
            }

        # If paths are specified, fetch L1
        if paths:
            l1_list = []
            for path in paths:
                l1 = loader.load_l1(path)
                if l1:
                    l1_list.append(l1)
            return {
                "level": "l1",
                "content": "\n\n---\n\n".join(l1.to_text() for l1 in l1_list),
                "files": [l1.path for l1 in l1_list],
            }

        # If query is provided, use L0 to locate then fetch L2
        if query:
            l2_list = loader.load_l2_by_query(query, top_k=5)
            return {
                "level": "l2",
                "query": query,
                "content": "\n\n---\n\n".join(l2.to_text() for l2 in l2_list if l2),
                "symbols": [l2.symbol_id for l2 in l2_list if l2],
                "l0_summary": f"Project has {len(self.index.files)} files, {len(self.index.symbols)} symbols",
            }

        return {"error": "No query, paths, or symbols provided"}

    def outline(self) -> str:
        """
        Generate project outline (L0) as text

        This is for AI consumption, used for quick navigation
        """
        loader = ContextLoader(self.index)
        l0 = loader.load_l0()
        return l0.to_text()

    # ------------------------------------------------------------------
    # Private helpers (lifecycle, serialization)
    # ------------------------------------------------------------------

    def _get_scanner(self, file_path: Path):
        """Get the matching scanner"""
        for scanner in self.scanners:
            if scanner.can_scan(file_path):
                return scanner
        return None

    def _resolve_symbol_id(self, symbol_id: str) -> Optional[str]:
        """Resolve symbol ID (supports short format)"""
        # Full format
        if symbol_id in self.index.symbols:
            return symbol_id

        # Short format: prepend project name
        full_id = f"{self.project_name}:{symbol_id}"
        if full_id in self.index.symbols:
            return full_id

        # Exact name match (match the last colon-separated segment)
        for sid in self.index.symbols:
            if sid.endswith(f":{symbol_id}"):
                return sid

        return None

    def _symbol_ref(self, symbol_id: str) -> dict:
        """Return a stable symbol reference, even for reverse-index-only IDs."""
        if symbol_id in self.index.symbols:
            symbol = self.index.symbols[symbol_id]
            return {
                "id": symbol_id,
                "path": symbol.path,
                "type": symbol.symbol_type.value,
                "name": symbol.name,
                "resolved": True,
            }

        parts = symbol_id.split(":", 3)
        if len(parts) == 4:
            _project, path, symbol_type, name = parts
        else:
            path = ""
            symbol_type = "unknown"
            name = symbol_id

        return {
            "id": symbol_id,
            "path": path,
            "type": symbol_type,
            "name": name,
            "resolved": False,
        }

    def _file_symbol_for_manifest(self, manifest: FileManifest) -> Symbol:
        """Create the canonical file-level symbol used by import dependencies."""
        path = Path(manifest.path)
        return Symbol(
            project=self.project_name,
            path=manifest.path,
            symbol_type=SymbolType.FILE,
            name=path.stem,
            start_line=1 if manifest.line_count else 0,
            end_line=manifest.line_count,
            content="",
            content_hash=manifest.content_hash,
            summary=f"File {manifest.path}",
            language=self._language_for_path(path),
        )

    @staticmethod
    def _language_for_path(path: Path) -> str:
        """Infer a stable language label from a source path."""
        suffix = path.suffix.lower()
        return {
            ".py": "python",
            ".ts": "typescript",
            ".tsx": "typescript",
            ".js": "javascript",
            ".jsx": "javascript",
            ".vue": "vue",
            ".go": "go",
            ".rs": "rust",
            ".java": "java",
        }.get(suffix, suffix[1:] if suffix else "")

    def _load_or_create_index(self) -> ProjectIndex:
        """Load or create index"""
        index_file = self.index_dir / "index.json"
        if index_file.exists():
            try:
                data = json.loads(index_file.read_text())
                return self._deserialize_index(data)
            except (json.JSONDecodeError, KeyError, OSError) as e:
                logger.warning("Failed to load index from %s: %s", index_file, e)
        return self._create_empty_index()

    def _create_empty_index(self) -> ProjectIndex:
        """Create empty index"""
        return ProjectIndex(
            project=self.project_name,
            root_path=str(self.project_root),
        )

    def _update_index(self, result: ScanResult, changes=None):
        """Update index"""
        # For incremental update, first remove old data for changed files
        if changes:
            for path in changes.all_changed() + changes.deleted:
                # Remove old symbols
                to_remove = [
                    sid for sid in self.index.symbols
                    if self.index.symbols[sid].path == path
                ]
                for sid in to_remove:
                    del self.index.symbols[sid]

                # Remove old dependencies
                to_remove = [
                    did for did, dep in self.index.dependencies.items()
                    if dep.source_id.startswith(f"{self.project_name}:{path}:")
                ]
                for did in to_remove:
                    del self.index.dependencies[did]

                # Remove old manifest
                if path in self.index.files:
                    del self.index.files[path]

        # Add new data
        for symbol in result.symbols:
            self.index.symbols[symbol.id] = symbol

        for manifest in result.manifests:
            file_symbol = self._file_symbol_for_manifest(manifest)
            self.index.symbols[file_symbol.id] = file_symbol
            if file_symbol.id not in manifest.symbols:
                manifest.symbols.insert(0, file_symbol.id)

        for dep in result.dependencies:
            self.index.dependencies[dep.id] = dep

        for manifest in result.manifests:
            self.index.files[manifest.path] = manifest

    def _save_index(self, separate_content: bool = True):
        """
        Save index

        Args:
            separate_content: If True, save content to content.jsonl separately
        """
        self.index_dir.mkdir(parents=True, exist_ok=True)
        _ensure_gitignore(self.index_dir)
        _ensure_ide_exclude(self.project_root)
        index_file = self.index_dir / "index.json"
        content_file = self.index_dir / "content.jsonl"

        # Save content to JSONL if requested (atomic write)
        if separate_content:
            def _content_lines():
                for symbol in self.index.symbols.values():
                    if symbol.content:
                        record = symbol.to_content_record()
                        yield json.dumps(record, ensure_ascii=False) + '\n'
            atomic_write_lines(content_file, _content_lines())

        # Main index without content (compact mode)
        data = {
            "project": self.index.project,
            "root_path": self.index.root_path,
            "indexed_at": datetime.now().isoformat(),
            "files": {k: v.to_dict() for k, v in self.index.files.items()},
            "symbols": {
                k: v.to_dict(include_content=not separate_content, compact=True)
                for k, v in self.index.symbols.items()
            },
            "dependencies": {k: v.to_dict() for k, v in self.index.dependencies.items()},
            "entry_points": self.index.entry_points,
            "routes": self.index.routes,
            "api_endpoints": self.index.api_endpoints,
            "reverse_index": self.index.reverse_index,
            "has_content_file": separate_content,
        }

        atomic_write_json(index_file, data)

        # Bump generation counter so in-memory caches know to reload
        try:
            from .index_store import _write_generation
        except ImportError:
            from index_store import _write_generation
        _write_generation(self.index_dir)

    def _deserialize_index(self, data: dict) -> ProjectIndex:
        """Deserialize index from JSON"""
        index = ProjectIndex(
            project=data["project"],
            root_path=data["root_path"],
            entry_points=data.get("entry_points", []),
            routes=data.get("routes", {}),
            api_endpoints=data.get("api_endpoints", []),
            reverse_index=data.get("reverse_index", {}),
        )

        # Restore files
        for path, fdata in data.get("files", {}).items():
            index.files[path] = FileManifest(
                path=fdata["path"],
                content_hash=fdata["hash"],
                line_count=fdata["lines"],
                symbols=fdata.get("symbols", []),
                last_indexed=fdata.get("indexed_at", ""),
            )

        # Load content from JSONL if available
        content_map = {}
        if data.get("has_content_file"):
            content_file = self.index_dir / "content.jsonl"
            if content_file.exists():
                content_map = self._load_content_file(content_file)

        # Restore symbols
        for sid, sdata in data.get("symbols", {}).items():
            # Get content from content_map or from inline data
            content = content_map.get(sid, sdata.get("content", ""))

            index.symbols[sid] = Symbol(
                project=sdata["project"],
                path=sdata["path"],
                symbol_type=SymbolType(sdata["type"]),
                name=sdata["name"],
                start_line=sdata.get("start_line", 0),
                end_line=sdata.get("end_line", 0),
                content=content,
                content_hash=sdata.get("content_hash", ""),
                summary=sdata.get("summary", ""),
                language=sdata.get("language", ""),
                exports=sdata.get("exports", []),
                imports=sdata.get("imports", []),
                metadata=sdata.get("metadata", {}),
                reference_count=sdata.get("ref_count", 0),
            )

        # Restore dependencies
        for did, ddata in data.get("dependencies", {}).items():
            from .models import DependencyType
            index.dependencies[did] = Dependency(
                source_id=ddata["source"],
                target_id=ddata["target"],
                dep_type=DependencyType(ddata["type"]),
                source_line=ddata.get("line", 0),
                metadata=ddata.get("metadata", {}),
            )

        return index

    def _load_content_file(self, content_file: Path) -> dict:
        """Load content from JSONL file."""
        content_map = {}
        try:
            with open(content_file, 'r', encoding='utf-8') as f:
                for line in f:
                    line = line.strip()
                    if line:
                        record = json.loads(line)
                        content_map[record["id"]] = record["content"]
        except (json.JSONDecodeError, KeyError, OSError) as e:
            logger.warning("Failed to load content file %s: %s", content_file, e)
        return content_map
